In [1]:
import numpy as np

In [2]:
a=np.array[1
2
3
4
5
6
7
]
a

SyntaxError: invalid syntax (<ipython-input-2-a3cbf5855547>, line 2)

In [49]:
import numpy as np
import pandas as pd
import pyfeng as pf

import timer
# from tqdm import tqdm

In [ ]:
# # Van (2010)
# strike = [100.0, 140.0, 60.0]
# forward = 100
# delta = [1, 1/2, 1/4, 1/8, 1/16, 1/32]
# case = np.zeros([3, 7])
# #case[i]=[vov, kappa, rho, texp, theta,   sigma,    r]
# case[0] = [1,   0.5, -0.9, 10, 0.04, np.sqrt(0.04), 0]
# case[1] = [1,   1,   -0.3, 5,  0.09, np.sqrt(0.09), 0.05]
# case[2] = [0.9, 0.3, -0.5, 15, 0.04, np.sqrt(0.04), 0]
# ref_price = np.array([[13.085, 0.296, 44.330], [33.597, 18.157, 56.575], [16.649, 5.138, 45.287]])

In [54]:
vov = np.array([0.125, 0.250, 0.375])
strike = np.array([90, 100, 110])
rho=0
#texp = [0.5,1.0,1.5,2.0,10.0]

texp = np.array([0.5,1.0,1.5,2.0,10.0])

# sigma, mr, spot, theta, intr = 0.087, 2, 100, 0.09, 0.015 are constant
n_path = 200000
dt = 1 / 250
sigma, mr, spot, theta, intr = 0.087, 2, 100, 0.09, 0.015
vol_budget = 0.087

In [ ]:
# for vov in [0.125, 0.25, 0.375]:
#     for texp in [0.5, 1.0, 1.5, 2.0, 10.0]:
#         for rho in [0]:
#             for strike in [90, 100, 110]:
#                 m = pf.HestonMcAndersen2008(sigma, vov=vov, mr=mr, rho=rho, theta=theta, intr=intr)
#                 m.set_num_params(n_path=n_path, dt=dt, rn_seed=123456)

#                 cp = 1  # Timer option--call option
#                 print("vov(η)=", vov, "texp(T)=", texp, "rho(ρ)=", rho, "strike(K)=", strike, ": ", \
#                       timer.timeroption(vol_budget, model=m).price(spot=spot, strike=strike, texp=texp, cp=cp))


In [ ]:
# # Compare with QE-M method result given by Van (2010)
# i = 0
# vov, kappa, rho, texp, theta, sigma, r = case[i]
# price_cmc = pd.DataFrame(np.zeros([len(delta), len(strike)]), index=delta, columns=strike)
# bias_cmc = pd.DataFrame(np.zeros(price_cmc.shape), index=price_cmc.index, columns=price_cmc.columns)

# start = time.time()
# heston_cmc_qe = pf.HestonCondMcQE(vov=vov, kappa=kappa, rho=rho, theta=theta)

# for d in range(len(delta)):
#     price_cmc.iloc[d, :] = heston_cmc_qe.price(strike, forward, texp, sigma=sigma, delta=delta[d], intr=r, path=1e6, seed=123456)
#     bias_cmc.iloc[d, :] = price_cmc.iloc[d, :] - ref_price[i, :]

# end = time.time()

# np.set_printoptions(suppress=True)
# print('Case %s:\n' % i + 'price')
# print(price_cmc)
# print('bias')
# print(bias_cmc)
# print('Running time is %.3f seconds.' % (end - start) + '\n')

In [57]:
price_heston_mc = pd.DataFrame(np.zeros([len(strike), len(vov)]), index=strike, columns=vov)
m = pf.HestonMcAndersen2008(sigma, vov=vov, mr=mr, rho=rho, theta=theta, intr=intr)
m.set_num_params(n_path=n_path, dt=dt, rn_seed=123456)
# m.set_num_params(n_path=n_path, dt=dt, rn_seed=123456)
# heston_mc_qe = timer.timeroption(vol_budget, model=m).price(spot=spot, strike=strike, texp=0.5, cp=1)
for d in range(len(strike)):
    m = pf.HestonMcAndersen2008(sigma, vov=vov, mr=mr, rho=rho, theta=theta, intr=intr)
#     price_heston_mc[d, :] = timer.timeroption(vol_budget, model=m).price(spot=spot, strike=strike[d], texp=0.5, cp=1)
print(timer.timeroption(vol_budget, model=m).price(spot=spot, strike=strike[d], texp=texp, cp=1))    

TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
vov = [0.125, 0.250, 0.375]
srike = [90, 100, 110]

In [23]:
x="""14.3500
8.6894
4.8901
17.3649
12.1038
8.1919
17.6275
12.3945
8.4784
17.6277
12.3947
8.4786
17.6278
12.3948
8.4786"""
s=x.split('\n')
print(s)

['14.3500', '8.6894', '4.8901', '17.3649', '12.1038', '8.1919', '17.6275', '12.3945', '8.4784', '17.6277', '12.3947', '8.4786', '17.6278', '12.3948', '8.4786']


In [31]:
s_new=np.array(s)
ss_new = s_new.astype(float)
s_new,ss_new

(array(['14.3500', '8.6894', '4.8901', '17.3649', '12.1038', '8.1919',
        '17.6275', '12.3945', '8.4784', '17.6277', '12.3947', '8.4786',
        '17.6278', '12.3948', '8.4786'], dtype='<U7'),
 array([14.35  ,  8.6894,  4.8901, 17.3649, 12.1038,  8.1919, 17.6275,
        12.3945,  8.4784, 17.6277, 12.3947,  8.4786, 17.6278, 12.3948,
         8.4786]))

In [24]:
new_s=[]
for i in range(len(s)):
    for num in s[i]:
        new_s.append(float(num))
print(new_s)

ValueError: could not convert string to float: '.'

In [ ]:
# Compare with QE-M method result given by Van (2010)
i = 0
vov, kappa, rho, texp, theta, sigma, r = case[i]
price_cmc = pd.DataFrame(np.zeros([len(delta), len(strike)]), index=delta, columns=strike)
bias_cmc = pd.DataFrame(np.zeros(price_cmc.shape), index=price_cmc.index, columns=price_cmc.columns)

start = time.time()
heston_cmc_qe = pf.HestonCondMcQE(vov=vov, kappa=kappa, rho=rho, theta=theta)

for d in range(len(delta)):
    price_cmc.iloc[d, :] = heston_cmc_qe.price(strike, forward, texp, sigma=sigma, delta=delta[d], intr=r, path=1e6, seed=123456)
    bias_cmc.iloc[d, :] = price_cmc.iloc[d, :] - ref_price[i, :]

end = time.time()

np.set_printoptions(suppress=True)
print('Case %s:\n' % i + 'price')
print(price_cmc)
print('bias')
print(bias_cmc)
print('Running time is %.3f seconds.' % (end - start) + '\n')

In [17]:
import matplotlib.pyplot as plt  #画图用
import numpy as np
import matplotlib
import xlrd  				#读Excel数据用

In [75]:
# 试验维度
x = np.zeros([5,3,3]) #第一个5是T/texp的取值维度，第二个3是K/strike的取值维度，第三个3是vov的取值维度
x

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [119]:
# 试验
z = np.zeros([3,2,3,3])
for i in range(3):
    print('T = %s:' % i)
    for j in range(2):
        print('ρ= %s:' % j)
        for k in range(3):
            for l in range(3):
                z[i][j][k][l] = i+j+k+l
        print(pd.DataFrame(z[i][j][:][:]))
#             print(z[i][j][k][:])

        print('\n')

T = 0:
ρ= 0:
     0    1    2
0  0.0  1.0  2.0
1  1.0  2.0  3.0
2  2.0  3.0  4.0


ρ= 1:
     0    1    2
0  1.0  2.0  3.0
1  2.0  3.0  4.0
2  3.0  4.0  5.0


T = 1:
ρ= 0:
     0    1    2
0  1.0  2.0  3.0
1  2.0  3.0  4.0
2  3.0  4.0  5.0


ρ= 1:
     0    1    2
0  2.0  3.0  4.0
1  3.0  4.0  5.0
2  4.0  5.0  6.0


T = 2:
ρ= 0:
     0    1    2
0  2.0  3.0  4.0
1  3.0  4.0  5.0
2  4.0  5.0  6.0


ρ= 1:
     0    1    2
0  3.0  4.0  5.0
1  4.0  5.0  6.0
2  5.0  6.0  7.0




In [124]:
z = np.zeros([3,2,2])
z
dz=pd.DataFrame(z)
dz

ValueError: Must pass 2-d input

In [76]:
x[0][1][1]

0.0

In [79]:
import pyfeng as pf
import timer
import numpy as np

n_path = 200000
dt = 1 / 250

sigma, mr, spot, theta, intr = 0.087, 2, 100, 0.09, 0.015
vol_budget = 0.087  # Li M, Mercurio F (2015). Budget level is constant = 0.087

vov = np.array([0.125, 0.25, 0.375])
texp = np.array([0.5, 1.0, 1.5, 2.0, 10.0])
strike = np.array([90, 100, 110])

# for vov in [0.125, 0.25, 0.375]:
#     for texp in [0.5, 1.0, 1.5, 2.0, 10.0]:
#         for rho in [0]:
#             for strike in [90, 100, 110]:
#                 m = pf.HestonMcAndersen2008(sigma, vov=vov, mr=mr, rho=rho, theta=theta, intr=intr)
#                 m.set_num_params(n_path=n_path, dt=dt, rn_seed=123456)
#
#                 cp = 1  # Timer option--call option
#                 print("vov(η)=", vov, "texp(T)=", texp, "rho(ρ)=", rho, "strike(K)=", strike, ": ", \
#                       timer.timeroption(vol_budget, model=m).price(spot=spot, strike=strike, texp=texp, cp=cp))

rho = 0
cp = 1
for i in range(len(vov)):
    for j in range(len(texp)):
        for k in range(len(strike)):
            m = pf.HestonMcAndersen2008(sigma, vov=vov[i], mr=mr, rho=rho, theta=theta, intr=intr)
            m.set_num_params(n_path=n_path, dt=dt, rn_seed=123456)
            cp = 1
            x[j][k][i] = timer.timeroption(vol_budget, model=m).price(spot=spot, strike=strike[k], texp=texp[j], cp=cp)

In [80]:
x

array([[[14.34160091, 14.31691054, 14.26999203],
        [ 8.67647446,  8.63366821,  8.55452477],
        [ 4.88543919,  4.85241675,  4.79088315]],

       [[17.35199114, 17.06532512, 16.76035494],
        [12.08896684, 11.75426648, 11.39572367],
        [ 8.17238514,  7.84561551,  7.49212563]],

       [[17.62567505, 17.66718423, 17.57613136],
        [12.38781847, 12.41784448, 12.30075286],
        [ 8.46357213,  8.48782858,  8.36170497]],

       [[17.62598762, 17.69762593, 17.75043558],
        [12.38807825, 12.45158871, 12.4916606 ],
        [ 8.4638251 ,  8.52222176,  8.54776175]],

       [[17.62598762, 17.69839695, 17.76674403],
        [12.38807825, 12.45238177, 12.51004673],
        [ 8.4638251 ,  8.52309047,  8.56550553]]])

In [82]:
import pandas as pd
df=pd.DataFrame(x)
df

ValueError: Must pass 2-d input

In [83]:
y = np.zeros([5,3,3]) #第一个5是T/texp的取值维度，第二个3是K/strike的取值维度，第三个3是vov的取值维度
y

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
import pyfeng as pf
import timer
import numpy as np

n_path = 200000
dt = 1 / 250

sigma, mr, spot, theta, intr = 0.087, 2, 100, 0.09, 0.015
vol_budget = 0.087  # Li M, Mercurio F (2015). Budget level is constant = 0.087

vov = np.array([0.125, 0.25, 0.375])
texp = np.array([0.5, 1.0, 1.5, 2.0, 10.0])
strike = np.array([90, 100, 110])

# for vov in [0.125, 0.25, 0.375]:
#     for texp in [0.5, 1.0, 1.5, 2.0, 10.0]:
#         for rho in [0]:
#             for strike in [90, 100, 110]:
#                 m = pf.HestonMcAndersen2008(sigma, vov=vov, mr=mr, rho=rho, theta=theta, intr=intr)
#                 m.set_num_params(n_path=n_path, dt=dt, rn_seed=123456)
#
#                 cp = 1  # Timer option--call option
#                 print("vov(η)=", vov, "texp(T)=", texp, "rho(ρ)=", rho, "strike(K)=", strike, ": ", \
#                       timer.timeroption(vol_budget, model=m).price(spot=spot, strike=strike, texp=texp, cp=cp))

rho = 0
cp = 1
for i in range(len(vov)):
    for j in range(len(texp)):
        print('T =%s:\n' % texp(j) )
        for k in range(len(strike)):
            m = pf.HestonMcAndersen2008(sigma, vov=vov[i], mr=mr, rho=rho, theta=theta, intr=intr)
            m.set_num_params(n_path=n_path, dt=dt, rn_seed=123456)
            cp = 1
            x[j][k][i] = timer.timeroption(vol_budget, model=m).price(spot=spot, strike=strike[k], texp=texp[j], cp=cp)
            print(x[j][k][i])

In [86]:
i=0.5
print('T = %s:\n' % i)

T = 0.5:



In [ ]:
import pyfeng as pf
import timer
import numpy as np

n_path = 200000
dt = 1 / 250

sigma, mr, spot, theta, intr = 0.087, 2, 100, 0.09, 0.015
vol_budget = 0.087  # Li M, Mercurio F (2015). Budget level is constant = 0.087

vov = np.array([0.125, 0.25, 0.375])
texp = np.array([0.5, 1.0, 1.5, 2.0, 10.0])
strike = np.array([90, 100, 110])

In [ ]:
rho = 0
cp = 1

In [88]:
import pyfeng as pf
import timer
import numpy as np

n_path = 200000
dt = 1 / 250

sigma, mr, spot, theta, intr = 0.087, 2, 100, 0.09, 0.015
vol_budget = 0.087  # Li M, Mercurio F (2015). Budget level is constant = 0.087

vov = np.array([0.125, 0.25, 0.375])
texp = np.array([0.5, 1.0, 1.5, 2.0, 10.0])
strike = np.array([90, 100, 110])

# for vov in [0.125, 0.25, 0.375]:
#     for texp in [0.5, 1.0, 1.5, 2.0, 10.0]:
#         for rho in [0]:
#             for strike in [90, 100, 110]:
#                 m = pf.HestonMcAndersen2008(sigma, vov=vov, mr=mr, rho=rho, theta=theta, intr=intr)
#                 m.set_num_params(n_path=n_path, dt=dt, rn_seed=123456)
#
#                 cp = 1  # Timer option--call option
#                 print("vov(η)=", vov, "texp(T)=", texp, "rho(ρ)=", rho, "strike(K)=", strike, ": ", \
#                       timer.timeroption(vol_budget, model=m).price(spot=spot, strike=strike, texp=texp, cp=cp))

rho = 0
cp = 1

In [91]:
#以下是对的，但提前终止了
for i in range(len(texp)):
    print('T = %s:\n' % texp[i])
    for j in range(len(strike)):
        for k in range(len(vov)):
            m = pf.HestonMcAndersen2008(sigma, vov=vov[k], mr=mr, rho=rho, theta=theta, intr=intr)
            m.set_num_params(n_path=n_path, dt=dt, rn_seed=123456)
            cp = 1
            x[i][j][k] = timer.timeroption(vol_budget, model=m).price(spot=spot, strike=strike[j], texp=texp[i], cp=cp)
            print(x[i][j][k])

T = 0.5:

14.34160091358013
14.316910540093335
14.2699920342206
8.676474460906581
8.633668211241769
8.554524766658055
4.885439191043122


KeyboardInterrupt: 

In [92]:
y = np.zeros([5,3,3]) #第一个5是T/texp的取值维度，第二个3是K/strike的取值维度，第三个3是vov的取值维度
y

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [128]:
# 试验
for i in range(5):
    print('T = %s:' % texp[i])
    for j in range(len(strike)):
        for k in range(len(vov)):
            x[i][j][k] = i+j+k
    print(pd.DataFrame(x[i][:][:]))
    print('\n')

T = 0.5:
     0    1    2
0  0.0  1.0  2.0
1  1.0  2.0  3.0
2  2.0  3.0  4.0


T = 1.0:
     0    1    2
0  1.0  2.0  3.0
1  2.0  3.0  4.0
2  3.0  4.0  5.0


T = 1.5:
     0    1    2
0  2.0  3.0  4.0
1  3.0  4.0  5.0
2  4.0  5.0  6.0


T = 2.0:
     0    1    2
0  3.0  4.0  5.0
1  4.0  5.0  6.0
2  5.0  6.0  7.0


T = 10.0:
     0    1    2
0  4.0  5.0  6.0
1  5.0  6.0  7.0
2  6.0  7.0  8.0




In [110]:
# 以下才是最终代码！！
for i in range(len(texp)):
    print('T = %s:' % texp[i])
    for j in range(len(strike)):
        for k in range(len(vov)):
            m = pf.HestonMcAndersen2008(sigma, vov=vov[k], mr=mr, rho=rho, theta=theta, intr=intr)
            m.set_num_params(n_path=n_path, dt=dt, rn_seed=123456)
            cp = 1
            x[i][j][k] = timer.timeroption(vol_budget, model=m).price(spot=spot, strike=strike[j], texp=texp[i], cp=cp)
        print(x[i][j][:])
    print('\n')

T = 0.5:
[14.34160091 14.31691054 14.26999203]
[8.67647446 8.63366821 8.55452477]
[4.88543919 4.85241675 4.79088315]


T = 1.0:
[17.35199114 17.06532512 16.76035494]
[12.08896684 11.75426648 11.39572367]
[8.17238514 7.84561551 7.49212563]


T = 1.5:
[17.62567505 17.66718423 17.57613136]
[12.38781847 12.41784448 12.30075286]
[8.46357213 8.48782858 8.36170497]


T = 2.0:
[17.62598762 17.69762593 17.75043558]
[12.38807825 12.45158871 12.4916606 ]
[8.4638251  8.52222176 8.54776175]


T = 10.0:
[17.62598762 17.69839695 17.76674403]
[12.38807825 12.45238177 12.51004673]
[8.4638251  8.52309047 8.56550553]




In [125]:
# 试验
z = np.zeros([3,2,3,3])
for i in range(3):
    print('T = %s:' % i)
    for j in range(2):
        print('ρ= %s:' % j)
        for k in range(3):
            for l in range(3):
                z[i][j][k][l] = i+j+k+l
        print(pd.DataFrame(z[i][j][:][:]))
#             print(z[i][j][k][:])

        print('\n')

T = 0:
ρ= 0:
     0    1    2
0  0.0  1.0  2.0
1  1.0  2.0  3.0
2  2.0  3.0  4.0


ρ= 1:
     0    1    2
0  1.0  2.0  3.0
1  2.0  3.0  4.0
2  3.0  4.0  5.0


T = 1:
ρ= 0:
     0    1    2
0  1.0  2.0  3.0
1  2.0  3.0  4.0
2  3.0  4.0  5.0


ρ= 1:
     0    1    2
0  2.0  3.0  4.0
1  3.0  4.0  5.0
2  4.0  5.0  6.0


T = 2:
ρ= 0:
     0    1    2
0  2.0  3.0  4.0
1  3.0  4.0  5.0
2  4.0  5.0  6.0


ρ= 1:
     0    1    2
0  3.0  4.0  5.0
1  4.0  5.0  6.0
2  5.0  6.0  7.0




In [129]:
# 试验
for i in range(5):
    print('T = %s:' % texp[i])
    for j in range(len(strike)):
        for k in range(len(vov)):
            x[i][j][k] = i+j+k
    print(pd.DataFrame(x[i][:][:]))
    print('\n')

T = 0.5:
     0    1    2
0  0.0  1.0  2.0
1  1.0  2.0  3.0
2  2.0  3.0  4.0


T = 1.0:
     0    1    2
0  1.0  2.0  3.0
1  2.0  3.0  4.0
2  3.0  4.0  5.0


T = 1.5:
     0    1    2
0  2.0  3.0  4.0
1  3.0  4.0  5.0
2  4.0  5.0  6.0


T = 2.0:
     0    1    2
0  3.0  4.0  5.0
1  4.0  5.0  6.0
2  5.0  6.0  7.0


T = 10.0:
     0    1    2
0  4.0  5.0  6.0
1  5.0  6.0  7.0
2  6.0  7.0  8.0




In [140]:
# 试验
for i in range(5):
    print('T = %s:' % texp[i])
    for j in range(len(strike)):
        for k in range(len(vov)):
            x[i][j][k] = i+j+k
    # print(pd.DataFrame(x[i][:][:]))
    df1=pd.DataFrame(x[i][:][:],index=['K1=90','K2=100','K3=110'],columns=['$\rho_1$=0.125','η2=0.250','η3=0.375'])
    print(df1)
    print('\n')

T = 0.5:
        $\rho_1$=0.125  η2=0.250  η3=0.375
K1=90              0.0       1.0       2.0
K2=100             1.0       2.0       3.0
K3=110             2.0       3.0       4.0


T = 1.0:
        $\rho_1$=0.125  η2=0.250  η3=0.375
K1=90              1.0       2.0       3.0
K2=100             2.0       3.0       4.0
K3=110             3.0       4.0       5.0


T = 1.5:
        $\rho_1$=0.125  η2=0.250  η3=0.375
K1=90              2.0       3.0       4.0
K2=100             3.0       4.0       5.0
K3=110             4.0       5.0       6.0


T = 2.0:
        $\rho_1$=0.125  η2=0.250  η3=0.375
K1=90              3.0       4.0       5.0
K2=100             4.0       5.0       6.0
K3=110             5.0       6.0       7.0


T = 10.0:
        $\rho_1$=0.125  η2=0.250  η3=0.375
K1=90              4.0       5.0       6.0
K2=100             5.0       6.0       7.0
K3=110             6.0       7.0       8.0




In [145]:
# 试验
z = np.zeros([3,2,3,3])
for i in range(3):
    print('T = %s:' % i)
    for j in range(2):
        print('ρ= %s:' % j)
        for k in range(3):
            for l in range(3):
                z[i][j][k][l] = i+j+k+l
        # print(pd.DataFrame(z[i][j][:][:]))
        df1=pd.DataFrame(z[i][j][:][:],index=['K1=90','K2=100','K3=110'],columns=['η= 0.125','0.250','0.375'])
        print(df1)
        
#             print(z[i][j][k][:])

        print('\n')

T = 0:
ρ= 0:
        η= 0.125  0.250  0.375
K1=90        0.0    1.0    2.0
K2=100       1.0    2.0    3.0
K3=110       2.0    3.0    4.0


ρ= 1:
        η= 0.125  0.250  0.375
K1=90        1.0    2.0    3.0
K2=100       2.0    3.0    4.0
K3=110       3.0    4.0    5.0


T = 1:
ρ= 0:
        η= 0.125  0.250  0.375
K1=90        1.0    2.0    3.0
K2=100       2.0    3.0    4.0
K3=110       3.0    4.0    5.0


ρ= 1:
        η= 0.125  0.250  0.375
K1=90        2.0    3.0    4.0
K2=100       3.0    4.0    5.0
K3=110       4.0    5.0    6.0


T = 2:
ρ= 0:
        η= 0.125  0.250  0.375
K1=90        2.0    3.0    4.0
K2=100       3.0    4.0    5.0
K3=110       4.0    5.0    6.0


ρ= 1:
        η= 0.125  0.250  0.375
K1=90        3.0    4.0    5.0
K2=100       4.0    5.0    6.0
K3=110       5.0    6.0    7.0




In [1]:
import pyfeng as pf
import timer_mc # the timer option model
import numpy as np
import pandas as pd
import time

In [7]:
x=np.zeros([3,3])
dx=pd.DataFrame(x,index=['小明','小红','小兰'],columns=['语文','数学','英语'])
dx

语文   数学   英语
小明  0.0  0.0  0.0
小红  0.0  0.0  0.0
小兰  0.0  0.0  0.0

In [8]:
print(dx)

     语文   数学   英语
小明  0.0  0.0  0.0
小红  0.0  0.0  0.0
小兰  0.0  0.0  0.0


In [10]:
x=np.zeros([3,3])
for i in range(3):
    x[i]=[i,i^2,i^3]
dx=pd.DataFrame(x)
print(dx)

     0    1    2
0  0.0  2.0  3.0
1  1.0  3.0  2.0
2  2.0  0.0  1.0
